# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Pavel\Dropbox\mayaScripts\rigStudio2\picker\pickerWindow.ui'
#
# Created: Sun Aug 15 08:40:13 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

#from PySide2 import QtCore, QtGui, QtWidgets
try:
    from PySide2 import QtWidgets, QtGui, QtCore
except:
    from Qt import QtWidgets, QtGui, QtCore

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(896, 803)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.right_frame = QtWidgets.QFrame(Dialog)
        self.right_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.right_frame.setObjectName("right_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.right_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.new_char_btn = QtWidgets.QPushButton(self.frame_3)
        self.new_char_btn.setObjectName("new_char_btn")
        self.verticalLayout_5.addWidget(self.new_char_btn)
        self.save_char_btn = QtWidgets.QPushButton(self.frame_3)
        self.save_char_btn.setObjectName("save_char_btn")
        self.verticalLayout_5.addWidget(self.save_char_btn)
        self.delete_char_btn = QtWidgets.QPushButton(self.frame_3)
        self.delete_char_btn.setObjectName("delete_char_btn")
        self.verticalLayout_5.addWidget(self.delete_char_btn)
        self.load_btn = QtWidgets.QPushButton(self.frame_3)
        self.load_btn.setObjectName("load_btn")
        self.verticalLayout_5.addWidget(self.load_btn)
        self.saveAs_char_btn = QtWidgets.QPushButton(self.frame_3)
        self.saveAs_char_btn.setObjectName("saveAs_char_btn")
        self.verticalLayout_5.addWidget(self.saveAs_char_btn)
        self.verticalLayout_3.addWidget(self.frame_3)
        self.buttons_frame = QtWidgets.QFrame(self.right_frame)
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout_11.setSpacing(2)
        self.verticalLayout_11.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_27 = QtWidgets.QLabel(self.buttons_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_11.addWidget(self.label_27)
        self.polygon_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.polygon_btn.setObjectName("polygon_btn")
        self.verticalLayout_11.addWidget(self.polygon_btn)
        self.rect_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.rect_btn.setObjectName("rect_btn")
        self.verticalLayout_11.addWidget(self.rect_btn)
        self.circle_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.circle_btn.setObjectName("circle_btn")
        self.verticalLayout_11.addWidget(self.circle_btn)
        self.label_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.label_btn.setObjectName("label_btn")
        self.verticalLayout_11.addWidget(self.label_btn)
        self.text_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.text_btn.setObjectName("text_btn")
        self.verticalLayout_11.addWidget(self.text_btn)
        self.button_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.button_btn.setDefault(False)
        self.button_btn.setFlat(False)
        self.button_btn.setObjectName("button_btn")
        self.verticalLayout_11.addWidget(self.button_btn)
        self.delete_char_btn_4 = QtWidgets.QPushButton(self.buttons_frame)
        self.delete_char_btn_4.setEnabled(False)
        self.delete_char_btn_4.setObjectName("delete_char_btn_4")
        self.verticalLayout_11.addWidget(self.delete_char_btn_4)
        self.image_btn = QtWidgets.QPushButton(self.buttons_frame)
        self.image_btn.setObjectName("image_btn")
        self.verticalLayout_11.addWidget(self.image_btn)
        self.verticalLayout_3.addWidget(self.buttons_frame)
        self.background_frame = QtWidgets.QFrame(self.right_frame)
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.background_frame.setObjectName("background_frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.background_frame)
        self.verticalLayout_13.setSpacing(2)
        self.verticalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_28 = QtWidgets.QLabel(self.background_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_13.addWidget(self.label_28)
        self.background_set_btn = QtWidgets.QPushButton(self.background_frame)
        self.background_set_btn.setObjectName("background_set_btn")
        self.verticalLayout_13.addWidget(self.background_set_btn)
        self.background_clear_btn = QtWidgets.QPushButton(self.background_frame)
        self.background_clear_btn.setObjectName("background_clear_btn")
        self.verticalLayout_13.addWidget(self.background_clear_btn)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_16 = QtWidgets.QLabel(self.background_frame)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_8.addWidget(self.label_16)
        self.opacity_lineEdit = QtWidgets.QLineEdit(self.background_frame)
        self.opacity_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.opacity_lineEdit.setReadOnly(True)
        self.opacity_lineEdit.setClearButtonEnabled(False)
        self.opacity_lineEdit.setObjectName("opacity_lineEdit")
        self.horizontalLayout_8.addWidget(self.opacity_lineEdit)
        self.verticalLayout_13.addLayout(self.horizontalLayout_8)
        self.opacity_slider = QtWidgets.QSlider(self.background_frame)
        self.opacity_slider.setMaximum(100)
        self.opacity_slider.setProperty("value", 100)
        self.opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.opacity_slider.setObjectName("opacity_slider")
        self.verticalLayout_13.addWidget(self.opacity_slider)
        self.label_18 = QtWidgets.QLabel(self.background_frame)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_13.addWidget(self.label_18)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.back_offset_x_spinBox = QtWidgets.QSpinBox(self.background_frame)
        self.back_offset_x_spinBox.setMinimum(-1000)
        self.back_offset_x_spinBox.setMaximum(1000)
        self.back_offset_x_spinBox.setObjectName("back_offset_x_spinBox")
        self.horizontalLayout_11.addWidget(self.back_offset_x_spinBox)
        self.back_offset_y_spinBox = QtWidgets.QSpinBox(self.background_frame)
        self.back_offset_y_spinBox.setMinimum(-1000)
        self.back_offset_y_spinBox.setMaximum(1000)
        self.back_offset_y_spinBox.setObjectName("back_offset_y_spinBox")
        self.horizontalLayout_11.addWidget(self.back_offset_y_spinBox)
        self.verticalLayout_13.addLayout(self.horizontalLayout_11)
        self.back_flip_checkBox = QtWidgets.QCheckBox(self.background_frame)
        self.back_flip_checkBox.setChecked(False)
        self.back_flip_checkBox.setObjectName("back_flip_checkBox")
        self.verticalLayout_13.addWidget(self.back_flip_checkBox)
        self.verticalLayout_3.addWidget(self.background_frame)
        self.frame_5 = QtWidgets.QFrame(self.right_frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_15.setSpacing(4)
        self.verticalLayout_15.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.autorunScript_btn = QtWidgets.QPushButton(self.frame_5)
        self.autorunScript_btn.setObjectName("autorunScript_btn")
        self.verticalLayout_15.addWidget(self.autorunScript_btn)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.autorun_checkBox = QtWidgets.QCheckBox(self.frame_5)
        self.autorun_checkBox.setChecked(False)
        self.autorun_checkBox.setObjectName("autorun_checkBox")
        self.horizontalLayout_13.addWidget(self.autorun_checkBox)
        self.autorunRun_btn = QtWidgets.QPushButton(self.frame_5)
        self.autorunRun_btn.setMaximumSize(QtCore.QSize(40, 20))
        self.autorunRun_btn.setObjectName("autorunRun_btn")
        self.horizontalLayout_13.addWidget(self.autorunRun_btn)
        self.verticalLayout_15.addLayout(self.horizontalLayout_13)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.axises_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.axises_checkBox.setChecked(True)
        self.axises_checkBox.setObjectName("axises_checkBox")
        self.verticalLayout_3.addWidget(self.axises_checkBox)
        self.selection_border_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.selection_border_checkBox.setChecked(True)
        self.selection_border_checkBox.setObjectName("selection_border_checkBox")
        self.verticalLayout_3.addWidget(self.selection_border_checkBox)
        self.moveLock_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.moveLock_checkBox.setChecked(False)
        self.moveLock_checkBox.setObjectName("moveLock_checkBox")
        self.verticalLayout_3.addWidget(self.moveLock_checkBox)
        self.updateSelection_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.updateSelection_checkBox.setChecked(True)
        self.updateSelection_checkBox.setObjectName("updateSelection_checkBox")
        self.verticalLayout_3.addWidget(self.updateSelection_checkBox)
        self.showHidden_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.showHidden_checkBox.setChecked(True)
        self.showHidden_checkBox.setObjectName("showHidden_checkBox")
        self.verticalLayout_3.addWidget(self.showHidden_checkBox)
        self.tab_visibility_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.tab_visibility_checkBox.setChecked(False)
        self.tab_visibility_checkBox.setObjectName("tab_visibility_checkBox")
        self.verticalLayout_3.addWidget(self.tab_visibility_checkBox)
        self.tabBar_visibility_checkBox = QtWidgets.QCheckBox(self.right_frame)
        self.tabBar_visibility_checkBox.setEnabled(False)
        self.tabBar_visibility_checkBox.setChecked(True)
        self.tabBar_visibility_checkBox.setObjectName("tabBar_visibility_checkBox")
        self.verticalLayout_3.addWidget(self.tabBar_visibility_checkBox)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_5.addWidget(self.right_frame)
        self.main_vertical_layout = QtWidgets.QVBoxLayout()
        self.main_vertical_layout.setContentsMargins(-1, 0, -1, -1)
        self.main_vertical_layout.setObjectName("main_vertical_layout")
        self.char_selector_frame = QtWidgets.QFrame(Dialog)
        self.char_selector_frame.setEnabled(True)
        self.char_selector_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.char_selector_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.char_selector_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.char_selector_frame.setObjectName("char_selector_frame")
        self.verticalLayout_76 = QtWidgets.QVBoxLayout(self.char_selector_frame)
        self.verticalLayout_76.setSpacing(4)
        self.verticalLayout_76.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.character_label = QtWidgets.QLabel(self.char_selector_frame)
        self.character_label.setObjectName("character_label")
        self.horizontalLayout_9.addWidget(self.character_label)
        self.char_selector_cb = QtWidgets.QComboBox(self.char_selector_frame)
        self.char_selector_cb.setObjectName("char_selector_cb")
        self.horizontalLayout_9.addWidget(self.char_selector_cb)
        self.useMatchRig_label = QtWidgets.QLabel(self.char_selector_frame)
        self.useMatchRig_label.setObjectName("useMatchRig_label")
        self.horizontalLayout_9.addWidget(self.useMatchRig_label)
        self.useMatchRig_checkBox = QtWidgets.QCheckBox(self.char_selector_frame)
        self.useMatchRig_checkBox.setText("")
        self.useMatchRig_checkBox.setObjectName("useMatchRig_checkBox")
        self.horizontalLayout_9.addWidget(self.useMatchRig_checkBox)
        self.autoLoadPicker_btn = QtWidgets.QToolButton(self.char_selector_frame)
        self.autoLoadPicker_btn.setMinimumSize(QtCore.QSize(50, 25))
        self.autoLoadPicker_btn.setMaximumSize(QtCore.QSize(50, 25))
        self.autoLoadPicker_btn.setIconSize(QtCore.QSize(32, 32))
        self.autoLoadPicker_btn.setCheckable(True)
        self.autoLoadPicker_btn.setAutoRaise(True)
        self.autoLoadPicker_btn.setObjectName("autoLoadPicker_btn")
        self.horizontalLayout_9.addWidget(self.autoLoadPicker_btn)
        self.horizontalLayout_9.setStretch(1, 1)
        self.verticalLayout_76.addLayout(self.horizontalLayout_9)
        self.main_vertical_layout.addWidget(self.char_selector_frame)
        self.data_frame = QtWidgets.QFrame(Dialog)
        self.data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.data_frame.setObjectName("data_frame")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.data_frame)
        self.verticalLayout_14.setSpacing(6)
        self.verticalLayout_14.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_29 = QtWidgets.QLabel(self.data_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.data_frame)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.name_lineEdit = QtWidgets.QLineEdit(self.data_frame)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.horizontalLayout_10.addWidget(self.name_lineEdit)
        self.rename_btn = QtWidgets.QPushButton(self.data_frame)
        self.rename_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.rename_btn.setMaximumSize(QtCore.QSize(60, 20))
        self.rename_btn.setObjectName("rename_btn")
        self.horizontalLayout_10.addWidget(self.rename_btn)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.main_vertical_layout.addWidget(self.data_frame)
        self.tab_widget_delete = QtWidgets.QTabWidget(Dialog)
        self.tab_widget_delete.setDocumentMode(False)
        self.tab_widget_delete.setTabBarAutoHide(False)
        self.tab_widget_delete.setObjectName("tab_widget_delete")
        self.main_vertical_layout.addWidget(self.tab_widget_delete)
        self.horizontalLayout_5.addLayout(self.main_vertical_layout)
        self.left_frame = QtWidgets.QFrame(Dialog)
        self.left_frame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame.sizePolicy().hasHeightForWidth())
        self.left_frame.setSizePolicy(sizePolicy)
        self.left_frame.setMinimumSize(QtCore.QSize(350, 0))
        self.left_frame.setMaximumSize(QtCore.QSize(350, 16777215))
        self.left_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_frame.setObjectName("left_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.left_frame)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.shape_frame = QtWidgets.QFrame(self.left_frame)
        self.shape_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.shape_frame.setObjectName("shape_frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.shape_frame)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_22 = QtWidgets.QLabel(self.shape_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_8.addWidget(self.label_22)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_opacity_slider = QtWidgets.QSlider(self.shape_frame)
        self.btn_opacity_slider.setMaximum(255)
        self.btn_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.btn_opacity_slider.setObjectName("btn_opacity_slider")
        self.gridLayout_4.addWidget(self.btn_opacity_slider, 0, 3, 1, 1)
        self.radius_label = QtWidgets.QLabel(self.shape_frame)
        self.radius_label.setObjectName("radius_label")
        self.gridLayout_4.addWidget(self.radius_label, 2, 0, 1, 1)
        self.squash_label = QtWidgets.QLabel(self.shape_frame)
        self.squash_label.setObjectName("squash_label")
        self.gridLayout_4.addWidget(self.squash_label, 2, 2, 1, 1)
        self.width_label = QtWidgets.QLabel(self.shape_frame)
        self.width_label.setObjectName("width_label")
        self.gridLayout_4.addWidget(self.width_label, 1, 0, 1, 1)
        self.btn_opacity_lineEdit = QtWidgets.QLineEdit(self.shape_frame)
        self.btn_opacity_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_opacity_lineEdit.setReadOnly(True)
        self.btn_opacity_lineEdit.setClearButtonEnabled(False)
        self.btn_opacity_lineEdit.setObjectName("btn_opacity_lineEdit")
        self.gridLayout_4.addWidget(self.btn_opacity_lineEdit, 0, 4, 1, 1)
        self.height_label = QtWidgets.QLabel(self.shape_frame)
        self.height_label.setObjectName("height_label")
        self.gridLayout_4.addWidget(self.height_label, 1, 2, 1, 1)
        self.opacity_label = QtWidgets.QLabel(self.shape_frame)
        self.opacity_label.setObjectName("opacity_label")
        self.gridLayout_4.addWidget(self.opacity_label, 0, 2, 1, 1)
        self.radius_spinBox = QtWidgets.QSpinBox(self.shape_frame)
        self.radius_spinBox.setMaximum(100)
        self.radius_spinBox.setObjectName("radius_spinBox")
        self.gridLayout_4.addWidget(self.radius_spinBox, 2, 1, 1, 1)
        self.width_spinBox = QtWidgets.QSpinBox(self.shape_frame)
        self.width_spinBox.setMinimum(-1000)
        self.width_spinBox.setMaximum(1000)
        self.width_spinBox.setObjectName("width_spinBox")
        self.gridLayout_4.addWidget(self.width_spinBox, 1, 1, 1, 1)
        self.color_label = QtWidgets.QLabel(self.shape_frame)
        self.color_label.setObjectName("color_label")
        self.gridLayout_4.addWidget(self.color_label, 0, 0, 1, 1)
        self.squash_spinBox = QtWidgets.QDoubleSpinBox(self.shape_frame)
        self.squash_spinBox.setMaximum(10.0)
        self.squash_spinBox.setSingleStep(0.1)
        self.squash_spinBox.setProperty("value", 1.0)
        self.squash_spinBox.setObjectName("squash_spinBox")
        self.gridLayout_4.addWidget(self.squash_spinBox, 2, 3, 1, 1)
        self.color_button = QtWidgets.QPushButton(self.shape_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.color_button.sizePolicy().hasHeightForWidth())
        self.color_button.setSizePolicy(sizePolicy)
        self.color_button.setMinimumSize(QtCore.QSize(100, 0))
        self.color_button.setMaximumSize(QtCore.QSize(100, 20))
        self.color_button.setObjectName("color_button")
        self.gridLayout_4.addWidget(self.color_button, 0, 1, 1, 1)
        self.height_spinBox = QtWidgets.QSpinBox(self.shape_frame)
        self.height_spinBox.setMinimum(-1000)
        self.height_spinBox.setMaximum(1000)
        self.height_spinBox.setObjectName("height_spinBox")
        self.gridLayout_4.addWidget(self.height_spinBox, 1, 3, 1, 1)
        self.radius_label_2 = QtWidgets.QLabel(self.shape_frame)
        self.radius_label_2.setObjectName("radius_label_2")
        self.gridLayout_4.addWidget(self.radius_label_2, 3, 0, 1, 1)
        self.visibility_checkBox = QtWidgets.QCheckBox(self.shape_frame)
        self.visibility_checkBox.setText("")
        self.visibility_checkBox.setObjectName("visibility_checkBox")
        self.gridLayout_4.addWidget(self.visibility_checkBox, 3, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_4)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.path_label = QtWidgets.QLabel(self.shape_frame)
        self.path_label.setObjectName("path_label")
        self.horizontalLayout_14.addWidget(self.path_label)
        self.path_lineEdit = QtWidgets.QLineEdit(self.shape_frame)
        self.path_lineEdit.setReadOnly(True)
        self.path_lineEdit.setObjectName("path_lineEdit")
        self.horizontalLayout_14.addWidget(self.path_lineEdit)
        self.setImagePath_btn = QtWidgets.QPushButton(self.shape_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setImagePath_btn.sizePolicy().hasHeightForWidth())
        self.setImagePath_btn.setSizePolicy(sizePolicy)
        self.setImagePath_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.setImagePath_btn.setMaximumSize(QtCore.QSize(40, 20))
        self.setImagePath_btn.setObjectName("setImagePath_btn")
        self.horizontalLayout_14.addWidget(self.setImagePath_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.editShape_btn = QtWidgets.QPushButton(self.shape_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editShape_btn.sizePolicy().hasHeightForWidth())
        self.editShape_btn.setSizePolicy(sizePolicy)
        self.editShape_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.editShape_btn.setMaximumSize(QtCore.QSize(10000, 20))
        self.editShape_btn.setObjectName("editShape_btn")
        self.horizontalLayout_3.addWidget(self.editShape_btn)
        self.verticalLayout_8.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4.addWidget(self.shape_frame)
        self.label_frame = QtWidgets.QFrame(self.left_frame)
        self.label_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_frame.setObjectName("label_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.label_frame)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_20 = QtWidgets.QLabel(self.label_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_7.addWidget(self.label_20)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_14 = QtWidgets.QLabel(self.label_frame)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.label_frame)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 1, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.label_frame)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_lineEdit = QtWidgets.QLineEdit(self.label_frame)
        self.label_lineEdit.setObjectName("label_lineEdit")
        self.gridLayout.addWidget(self.label_lineEdit, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.label_frame)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_color_btn = QtWidgets.QPushButton(self.label_frame)
        self.label_color_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.label_color_btn.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_color_btn.setObjectName("label_color_btn")
        self.gridLayout.addWidget(self.label_color_btn, 1, 1, 1, 1)
        self.label_size_spinBox = QtWidgets.QSpinBox(self.label_frame)
        self.label_size_spinBox.setObjectName("label_size_spinBox")
        self.gridLayout.addWidget(self.label_size_spinBox, 0, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_opacity_slider = QtWidgets.QSlider(self.label_frame)
        self.label_opacity_slider.setMaximum(255)
        self.label_opacity_slider.setOrientation(QtCore.Qt.Horizontal)
        self.label_opacity_slider.setObjectName("label_opacity_slider")
        self.horizontalLayout.addWidget(self.label_opacity_slider)
        self.label_opacity_lineEdit = QtWidgets.QLineEdit(self.label_frame)
        self.label_opacity_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_opacity_lineEdit.setReadOnly(True)
        self.label_opacity_lineEdit.setClearButtonEnabled(False)
        self.label_opacity_lineEdit.setObjectName("label_opacity_lineEdit")
        self.horizontalLayout.addWidget(self.label_opacity_lineEdit)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.label_frame)
        self.frame_4 = QtWidgets.QFrame(self.left_frame)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.item_y_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.item_y_spinBox.setMinimum(-1000)
        self.item_y_spinBox.setMaximum(1000)
        self.item_y_spinBox.setObjectName("item_y_spinBox")
        self.gridLayout_3.addWidget(self.item_y_spinBox, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.item_x_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.item_x_spinBox.setMinimum(-1000)
        self.item_x_spinBox.setMaximum(1000)
        self.item_x_spinBox.setObjectName("item_x_spinBox")
        self.gridLayout_3.addWidget(self.item_x_spinBox, 0, 1, 1, 1)
        self.rotate_label = QtWidgets.QLabel(self.frame_4)
        self.rotate_label.setObjectName("rotate_label")
        self.gridLayout_3.addWidget(self.rotate_label, 1, 0, 1, 1)
        self.rotate_spinBox = QtWidgets.QSpinBox(self.frame_4)
        self.rotate_spinBox.setMinimum(-1000)
        self.rotate_spinBox.setMaximum(1000)
        self.rotate_spinBox.setObjectName("rotate_spinBox")
        self.gridLayout_3.addWidget(self.rotate_spinBox, 1, 1, 1, 1)
        self.flip_label = QtWidgets.QLabel(self.frame_4)
        self.flip_label.setObjectName("flip_label")
        self.gridLayout_3.addWidget(self.flip_label, 1, 2, 1, 1)
        self.flip_checkBox = QtWidgets.QCheckBox(self.frame_4)
        self.flip_checkBox.setText("")
        self.flip_checkBox.setObjectName("flip_checkBox")
        self.gridLayout_3.addWidget(self.flip_checkBox, 1, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.clickCommand_frame = QtWidgets.QFrame(self.left_frame)
        self.clickCommand_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.clickCommand_frame.setObjectName("clickCommand_frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.clickCommand_frame)
        self.verticalLayout_9.setSpacing(6)
        self.verticalLayout_9.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_23 = QtWidgets.QLabel(self.clickCommand_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_9.addWidget(self.label_23)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selection_btn = QtWidgets.QRadioButton(self.clickCommand_frame)
        self.selection_btn.setChecked(True)
        self.selection_btn.setObjectName("selection_btn")
        self.horizontalLayout_2.addWidget(self.selection_btn)
        self.pythonScript_btn = QtWidgets.QRadioButton(self.clickCommand_frame)
        self.pythonScript_btn.setObjectName("pythonScript_btn")
        self.horizontalLayout_2.addWidget(self.pythonScript_btn)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.setSelection_btn = QtWidgets.QPushButton(self.clickCommand_frame)
        self.setSelection_btn.setEnabled(True)
        self.setSelection_btn.setObjectName("setSelection_btn")
        self.horizontalLayout_7.addWidget(self.setSelection_btn)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setSpacing(2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.editScript_btn = QtWidgets.QPushButton(self.clickCommand_frame)
        self.editScript_btn.setEnabled(False)
        self.editScript_btn.setObjectName("editScript_btn")
        self.horizontalLayout_12.addWidget(self.editScript_btn)
        self.runScript_btn = QtWidgets.QPushButton(self.clickCommand_frame)
        self.runScript_btn.setEnabled(True)
        self.runScript_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.runScript_btn.setObjectName("runScript_btn")
        self.horizontalLayout_12.addWidget(self.runScript_btn)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_12)
        self.verticalLayout_9.addLayout(self.horizontalLayout_7)
        self.verticalLayout_4.addWidget(self.clickCommand_frame)
        self.rmb_frame = QtWidgets.QFrame(self.left_frame)
        self.rmb_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.rmb_frame.setObjectName("rmb_frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.rmb_frame)
        self.verticalLayout_10.setSpacing(6)
        self.verticalLayout_10.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_26 = QtWidgets.QLabel(self.rmb_frame)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rmb_listWidget = QtWidgets.QListWidget(self.rmb_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rmb_listWidget.sizePolicy().hasHeightForWidth())
        self.rmb_listWidget.setSizePolicy(sizePolicy)
        self.rmb_listWidget.setMaximumSize(QtCore.QSize(1000000, 16777215))
        self.rmb_listWidget.setObjectName("rmb_listWidget")
        self.horizontalLayout_4.addWidget(self.rmb_listWidget)
        self.frame = QtWidgets.QFrame(self.rmb_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_12.setSpacing(2)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rmb_add_btn = QtWidgets.QPushButton(self.frame)
        self.rmb_add_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rmb_add_btn.setObjectName("rmb_add_btn")
        self.horizontalLayout_6.addWidget(self.rmb_add_btn)
        self.rmb_remove_btn = QtWidgets.QPushButton(self.frame)
        self.rmb_remove_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rmb_remove_btn.setObjectName("rmb_remove_btn")
        self.horizontalLayout_6.addWidget(self.rmb_remove_btn)
        self.rmb_up_btn = QtWidgets.QPushButton(self.frame)
        self.rmb_up_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rmb_up_btn.setObjectName("rmb_up_btn")
        self.horizontalLayout_6.addWidget(self.rmb_up_btn)
        self.rmb_down_btn = QtWidgets.QPushButton(self.frame)
        self.rmb_down_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.rmb_down_btn.setObjectName("rmb_down_btn")
        self.horizontalLayout_6.addWidget(self.rmb_down_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_6)
        self.rmb_editScript_btn = QtWidgets.QPushButton(self.frame)
        self.rmb_editScript_btn.setObjectName("rmb_editScript_btn")
        self.verticalLayout_12.addWidget(self.rmb_editScript_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.horizontalLayout_4.addWidget(self.frame)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.addWidget(self.rmb_frame)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setSpacing(2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.path_label_2 = QtWidgets.QLabel(self.left_frame)
        self.path_label_2.setObjectName("path_label_2")
        self.horizontalLayout_15.addWidget(self.path_label_2)
        self.obj_name_lineEdit = QtWidgets.QLineEdit(self.left_frame)
        self.obj_name_lineEdit.setReadOnly(True)
        self.obj_name_lineEdit.setObjectName("obj_name_lineEdit")
        self.horizontalLayout_15.addWidget(self.obj_name_lineEdit)
        self.obj_name_set_btn = QtWidgets.QPushButton(self.left_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.obj_name_set_btn.sizePolicy().hasHeightForWidth())
        self.obj_name_set_btn.setSizePolicy(sizePolicy)
        self.obj_name_set_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.obj_name_set_btn.setMaximumSize(QtCore.QSize(40, 20))
        self.obj_name_set_btn.setObjectName("obj_name_set_btn")
        self.horizontalLayout_15.addWidget(self.obj_name_set_btn)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.initScript_btn = QtWidgets.QPushButton(self.left_frame)
        self.initScript_btn.setEnabled(True)
        self.initScript_btn.setObjectName("initScript_btn")
        self.verticalLayout_4.addWidget(self.initScript_btn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.verticalLayout_4.setStretch(7, 1)
        self.horizontalLayout_5.addWidget(self.left_frame)
        self.horizontalLayout_5.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.tab_widget_delete.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "RigStudio Picker", None, -1))
        self.new_char_btn.setText(QtWidgets.QApplication.translate("Dialog", "New", None, -1))
        self.save_char_btn.setText(QtWidgets.QApplication.translate("Dialog", "Save", None, -1))
        self.delete_char_btn.setText(QtWidgets.QApplication.translate("Dialog", "Delete", None, -1))
        self.load_btn.setText(QtWidgets.QApplication.translate("Dialog", "Load..", None, -1))
        self.saveAs_char_btn.setText(QtWidgets.QApplication.translate("Dialog", "Export..", None, -1))
        self.label_27.setText(QtWidgets.QApplication.translate("Dialog", "Buttons", None, -1))
        self.polygon_btn.setText(QtWidgets.QApplication.translate("Dialog", "Polygon", None, -1))
        self.rect_btn.setText(QtWidgets.QApplication.translate("Dialog", "Rectangle", None, -1))
        self.circle_btn.setText(QtWidgets.QApplication.translate("Dialog", "Circle", None, -1))
        self.label_btn.setText(QtWidgets.QApplication.translate("Dialog", "Label", None, -1))
        self.text_btn.setText(QtWidgets.QApplication.translate("Dialog", "Text", None, -1))
        self.button_btn.setText(QtWidgets.QApplication.translate("Dialog", "Button", None, -1))
        self.delete_char_btn_4.setText(QtWidgets.QApplication.translate("Dialog", "Slider", None, -1))
        self.image_btn.setText(QtWidgets.QApplication.translate("Dialog", "Image..", None, -1))
        self.label_28.setText(QtWidgets.QApplication.translate("Dialog", "Background", None, -1))
        self.background_set_btn.setText(QtWidgets.QApplication.translate("Dialog", "Set..", None, -1))
        self.background_clear_btn.setText(QtWidgets.QApplication.translate("Dialog", "Clear", None, -1))
        self.label_16.setText(QtWidgets.QApplication.translate("Dialog", "Opacity", None, -1))
        self.opacity_lineEdit.setText(QtWidgets.QApplication.translate("Dialog", "100", None, -1))
        self.label_18.setText(QtWidgets.QApplication.translate("Dialog", "Offset", None, -1))
        self.back_flip_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Flip", None, -1))
        self.autorunScript_btn.setText(QtWidgets.QApplication.translate("Dialog", "Edit Autorun Script..", None, -1))
        self.autorun_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Autorun", None, -1))
        self.autorunRun_btn.setText(QtWidgets.QApplication.translate("Dialog", "Run", None, -1))
        self.axises_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Center Axises", None, -1))
        self.selection_border_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Selection Border", None, -1))
        self.moveLock_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Move Lock", None, -1))
        self.updateSelection_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Update Selection", None, -1))
        self.showHidden_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Show Hidden", None, -1))
        self.tab_visibility_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "Visibility", None, -1))
        self.tabBar_visibility_checkBox.setText(QtWidgets.QApplication.translate("Dialog", "TabBar Visibility", None, -1))
        self.character_label.setText(QtWidgets.QApplication.translate("Dialog", "Picker", None, -1))
        self.useMatchRig_label.setText(QtWidgets.QApplication.translate("Dialog", "  Use External ", None, -1))
        self.autoLoadPicker_btn.setText(QtWidgets.QApplication.translate("Dialog", "...", None, -1))
        self.label_29.setText(QtWidgets.QApplication.translate("Dialog", "Data", None, -1))
        self.label_17.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.rename_btn.setText(QtWidgets.QApplication.translate("Dialog", "Rename..", None, -1))
        self.label_22.setText(QtWidgets.QApplication.translate("Dialog", "Shape", None, -1))
        self.radius_label.setText(QtWidgets.QApplication.translate("Dialog", "Radius", None, -1))
        self.squash_label.setText(QtWidgets.QApplication.translate("Dialog", "Squash", None, -1))
        self.width_label.setText(QtWidgets.QApplication.translate("Dialog", "Width", None, -1))
        self.btn_opacity_lineEdit.setText(QtWidgets.QApplication.translate("Dialog", "100", None, -1))
        self.height_label.setText(QtWidgets.QApplication.translate("Dialog", "Height", None, -1))
        self.opacity_label.setText(QtWidgets.QApplication.translate("Dialog", "Opacity", None, -1))
        self.color_label.setText(QtWidgets.QApplication.translate("Dialog", "Color", None, -1))
        self.color_button.setText(QtWidgets.QApplication.translate("Dialog", "Color", None, -1))
        self.radius_label_2.setText(QtWidgets.QApplication.translate("Dialog", "Visibility", None, -1))
        self.path_label.setText(QtWidgets.QApplication.translate("Dialog", "Path ", None, -1))
        self.setImagePath_btn.setText(QtWidgets.QApplication.translate("Dialog", "Set..", None, -1))
        self.editShape_btn.setText(QtWidgets.QApplication.translate("Dialog", "Edit Shape", None, -1))
        self.label_20.setText(QtWidgets.QApplication.translate("Dialog", "Label", None, -1))
        self.label_14.setText(QtWidgets.QApplication.translate("Dialog", "Color", None, -1))
        self.label_15.setText(QtWidgets.QApplication.translate("Dialog", "Opacity", None, -1))
        self.label_13.setText(QtWidgets.QApplication.translate("Dialog", "Text", None, -1))
        self.label_21.setText(QtWidgets.QApplication.translate("Dialog", "Size", None, -1))
        self.label_color_btn.setText(QtWidgets.QApplication.translate("Dialog", "Color", None, -1))
        self.label_opacity_lineEdit.setText(QtWidgets.QApplication.translate("Dialog", "100", None, -1))
        self.label_19.setText(QtWidgets.QApplication.translate("Dialog", "Transform", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "Position Y", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Position X", None, -1))
        self.rotate_label.setText(QtWidgets.QApplication.translate("Dialog", "Rotate", None, -1))
        self.flip_label.setText(QtWidgets.QApplication.translate("Dialog", "Flip X", None, -1))
        self.label_23.setText(QtWidgets.QApplication.translate("Dialog", "Click Command", None, -1))
        self.selection_btn.setText(QtWidgets.QApplication.translate("Dialog", "Selection", None, -1))
        self.pythonScript_btn.setText(QtWidgets.QApplication.translate("Dialog", "Python Script", None, -1))
        self.setSelection_btn.setText(QtWidgets.QApplication.translate("Dialog", "Set Selection", None, -1))
        self.editScript_btn.setText(QtWidgets.QApplication.translate("Dialog", "Edit Script..", None, -1))
        self.runScript_btn.setText(QtWidgets.QApplication.translate("Dialog", "Run", None, -1))
        self.label_26.setText(QtWidgets.QApplication.translate("Dialog", "Right Click Menu", None, -1))
        self.rmb_add_btn.setText(QtWidgets.QApplication.translate("Dialog", "+", None, -1))
        self.rmb_remove_btn.setText(QtWidgets.QApplication.translate("Dialog", "-", None, -1))
        self.rmb_up_btn.setText(QtWidgets.QApplication.translate("Dialog", "^", None, -1))
        self.rmb_down_btn.setText(QtWidgets.QApplication.translate("Dialog", "v", None, -1))
        self.rmb_editScript_btn.setText(QtWidgets.QApplication.translate("Dialog", "Edit Script..", None, -1))
        self.path_label_2.setText(QtWidgets.QApplication.translate("Dialog", "Name", None, -1))
        self.obj_name_set_btn.setText(QtWidgets.QApplication.translate("Dialog", "Set..", None, -1))
        self.initScript_btn.setText(QtWidgets.QApplication.translate("Dialog", "Initial Script..", None, -1))

